- name: Configure the host for the AS112 container
  hosts: as112_hosts
  gather_facts: false
  vars:
    container_name: as112

  tasks:
  - name: Create the container with debootstrap
    command:
      chdir: /var/lib/machines/
      cmd: >-
        debootstrap --variant=minbase
        --include=dbus,libpam-systemd,python3,ifupdown,procps
        --exclude=e2fsprogs
        bookworm {{container_name}}
        http://debian.seeweb.it/debian/
      creates: /var/lib/machines/{{container_name}}/

  - name: Configure the container hostname
    copy:
      dest: /var/lib/machines/{{container_name}}/etc/hostname
      content: "{{container_name}}.minap.it\n"

  - name: Configure the network
    copy: src=network-host/ dest=/etc/systemd/network/
    notify: Restart systemd-networkd

  - name: Create the directories
    file: state=directory path={{item.path}} mode={{ item.mode | default(omit) }}
    with_items:
    - { path: "/etc/systemd/system/systemd-nspawn@{{container_name}}.service.d/" }

  - name: Configure systemd-nspawn
    template: src=files/nspawn-br0-ixp dest="/etc/systemd/system/systemd-nspawn@{{container_name}}.service.d/local.conf"

  handlers:
  - name: Restart systemd-networkd
    systemd: name=systemd-networkd state=restarted

