- hosts: server1.minap.it
  gather_facts: false

  tasks:
    - name: Install the scripts in sbin
      copy:
        src: "{{item}}"
        dest: /usr/local/sbin/
        mode: '0755'
      with_items:
        - python3-container

    - name: Create symlinks for the python3-$container programs
      file:
        state: link
        src: python3-container
        dest: /usr/local/sbin/python3-{{item}}
      with_items:
        - as112
        - manager
        - rs1
        - sponge

    - name: Configure rsyslog to receive the server2 netconsole
      copy: src=netconsole.conf dest=/etc/rsyslog.d/
      notify: Restart rsyslog

  handlers:
  - name: Restart rsyslog
    systemd: name=rsyslog state=restarted

